export default [{
        id: 127,
        brand: "Modelo Especial",
        image: "/products/modelo-especial.jpeg",
        style: "Lager",
        substyle: "Light Lager",
        abv: "4.4%",
        origin: "Import",
        information: "A crisp, full-flavored Mexican lager brewed with a touch of sweetness and a clean finish. Modelo Especial strikes a perfect balance between light body and bold character, making it a favorite for social gatherings or sunny days.",
        rating: 5.0,
        skus: [
            { code: "10167", name: "12 - 24oz Cans" },
            { code: "10166", name: "18 - 12oz Cans" },
            { code: "10170", name: "Half Barrel" },
        ],
    },
    {
        id: 374,
        brand: "Miller Lite",
        image: "/products/miller-lite.png",
        style: "Lager",
        substyle: "Light Lager",
        abv: "4.17%",
        origin: "Wisconsin",
        information: "An American classic brewed for drinkability. Miller Lite is a refreshing light lager with subtle malt notes and a smooth finish, designed to keep things light without sacrificing taste.",
        skus: [
            { code: "10035", name: "24 - 12oz Bottles, 6 Pack" },
            { code: "10041", name: "24 - 12oz Bottles, 12 Pack" },
        ],
    },
    {
        id: 743,
        brand: "Corona Premier",
        image: "/products/corona.jpg",
        style: "Lager",
        substyle: "Mexican Lager",
        abv: "4.0%",
        origin: "Mexico",
        information: "A refined take on the classic Corona, Premier offers a lower calorie profile with the same smooth, crisp refreshment. Light in body, it's perfect for laid-back moments and sunny beach days.",
        rating: 2.9,
        skus: [
            { code: "35678", name: "24 - 12oz Bottles, 6 Pack" },
            { code: "35681", name: "Quarter Barrel Slim" },
        ],
    },
    {
        id: 841,
        brand: "Budweiser",
        image: "/products/budweiser.jpg",
        style: "Lager",
        substyle: "American Lager",
        abv: "5%",
        origin: "Missouri",
        information: "Known as 'The King of Beers', Budweiser delivers a medium-bodied, flavorful lager with subtle sweetness from rice and a balanced hoppy bitterness. It's a timeless American brew for every occasion.",
        rating: 3.9,
        skus: [
            { code: "15337", name: "24 - 12oz Bottles, 12 Pack" },
        ],
    },
];